export const CLINICAL_SIGNIFICANCE_LABEL: { [key: string]: string } = {
  CLINICAL_SIGNIFICANCE_PATHOGENIC: 'pathogenic',
  CLINICAL_SIGNIFICANCE_LIKELY_PATHOGENIC: 'likely pathogenic',
  CLINICAL_SIGNIFICANCE_UNCERTAIN_SIGNIFICANCE: 'uncertain significance',
  CLINICAL_SIGNIFICANCE_LIKELY_BENIGN: 'likely benign',
  CLINICAL_SIGNIFICANCE_BENIGN: 'benign'
}

export const CLINICAL_SIGNIFICANCE_COLOR: { [key: string]: string } = {
  CLINICAL_SIGNIFICANCE_PATHOGENIC: 'red-darken-3',
  CLINICAL_SIGNIFICANCE_LIKELY_PATHOGENIC: 'orange-draken-2',
  CLINICAL_SIGNIFICANCE_UNCERTAIN_SIGNIFICANCE: 'gray-lighten-2',
  CLINICAL_SIGNIFICANCE_LIKELY_BENIGN: 'green-lighen-3',
  CLINICAL_SIGNIFICANCE_BENIGN: 'green-darken-2'
}

export const REVIEW_STATUS_LABEL: { [key: string]: string } = {
  REVIEW_STATUS_PRACTICE_GUIDELINE: 'practice guideline',
  REVIEW_STATUS_REVIEWED_BY_EXPERT_PANEL: 'reviewed by expert panel',
  REVIEW_STATUS_CRITERIA_PROVIDED_MULTIPLE_SUBMITTERS_NO_CONFLICTS:
    'criteria provided, multiple submitters, no conflicts',
  REVIEW_STATUS_CRITERIA_PROVIDED_SINGLE_SUBMITTER: 'criteria provided, single submitter',
  REVIEW_STATUS_CRITERIA_PROVIDED_CONFLICTING_INTERPRETATIONS:
    'criteria provided, conflicting interpretations',
  REVIEW_STATUS_NO_ASSERTION_CRITERIA_PROVIDED: 'no assertion criteria provided',
  REVIEW_STATUS_NO_ASSERTION_PROVIDED: 'no assertion provided'
}

export const REVIEW_STATUS_STARS: { [key: string]: number } = {
  REVIEW_STATUS_PRACTICE_GUIDELINE: 4,
  REVIEW_STATUS_REVIEWED_BY_EXPERT_PANEL: 3,
  REVIEW_STATUS_CRITERIA_PROVIDED_MULTIPLE_SUBMITTERS_NO_CONFLICTS: 2,
  REVIEW_STATUS_CRITERIA_PROVIDED_SINGLE_SUBMITTER: 1,
  REVIEW_STATUS_CRITERIA_PROVIDED_CONFLICTING_INTERPRETATIONS: 0,
  REVIEW_STATUS_NO_ASSERTION_CRITERIA_PROVIDED: 0,
  REVIEW_STATUS_NO_ASSERTION_PROVIDED: 0
}
