version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install -r docs/requirements.txt
    - ls -a
    - pwd
    - cd backend
    - pwd
    - ls -a
    - make -C ./docs clean html
    - ls -a

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub

python:
   install:
     - requirements: docs/requirements.txt
