// This file is auto-generated by @hey-api/openapi-ts

export const VariantResponseSchema = {
    type: 'object',
    properties: {
        Intervar: {
            type: 'string',
            example: 'Uncertain significance'
        },
        Build: {
            type: 'string',
            example: 'hg19'
        },
        Chromosome: {
            type: 'integer',
            example: 17
        },
        Position: {
            type: 'integer',
            example: 41197728
        },
        Ref_allele: {
            type: 'string',
            example: 'G'
        },
        Alt_allele: {
            type: 'string',
            example: 'T'
        },
        Gene: {
            type: 'string',
            example: 'BRCA1'
        },
        PVS1: {
            type: 'integer',
            example: 0
        },
        PS1: {
            type: 'integer',
            example: 0
        },
        PS2: {
            type: 'integer',
            example: 0
        },
        PS3: {
            type: 'integer',
            example: 0
        },
        PS4: {
            type: 'integer',
            example: 0
        },
        PM1: {
            type: 'integer',
            example: 0
        },
        PM2: {
            type: 'integer',
            example: 1
        },
        PM3: {
            type: 'integer',
            example: 0
        },
        PM4: {
            type: 'integer',
            example: 0
        },
        PM5: {
            type: 'integer',
            example: 0
        },
        PM6: {
            type: 'integer',
            example: 0
        },
        PP1: {
            type: 'integer',
            example: 0
        },
        PP2: {
            type: 'integer',
            example: 0
        },
        PP3: {
            type: 'integer',
            example: 1
        },
        PP4: {
            type: 'integer',
            example: 0
        },
        PP5: {
            type: 'integer',
            example: 1
        },
        BA1: {
            type: 'integer',
            example: 0
        },
        BP1: {
            type: 'integer',
            example: 0
        },
        BP2: {
            type: 'integer',
            example: 0
        },
        BP3: {
            type: 'integer',
            example: 0
        },
        BP4: {
            type: 'integer',
            example: 0
        },
        BP5: {
            type: 'integer',
            example: 0
        },
        BP6: {
            type: 'integer',
            example: 0
        },
        BP7: {
            type: 'integer',
            example: 0
        },
        BS1: {
            type: 'integer',
            example: 0
        },
        BS2: {
            type: 'integer',
            example: 0
        },
        BS3: {
            type: 'integer',
            example: 0
        },
        BS4: {
            type: 'integer',
            example: 0
        }
    }
} as const;