// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetPositionData, GetPositionError, GetPositionResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Retrieves genetic variant annotations based on position.
 */
export const getPosition = <ThrowOnError extends boolean = false>(options: Options<GetPositionData, ThrowOnError>) => { return (options?.client ?? client).get<GetPositionResponse, GetPositionError, ThrowOnError>({
    ...options,
    url: '/api_new.php'
}); };