// This file is auto-generated by @hey-api/openapi-ts

export type VariantResponse = {
    Intervar?: string;
    Build?: string;
    Chromosome?: number;
    Position?: number;
    Ref_allele?: string;
    Alt_allele?: string;
    Gene?: string;
    PVS1?: number;
    PS1?: number;
    PS2?: number;
    PS3?: number;
    PS4?: number;
    PM1?: number;
    PM2?: number;
    PM3?: number;
    PM4?: number;
    PM5?: number;
    PM6?: number;
    PP1?: number;
    PP2?: number;
    PP3?: number;
    PP4?: number;
    PP5?: number;
    BA1?: number;
    BP1?: number;
    BP2?: number;
    BP3?: number;
    BP4?: number;
    BP5?: number;
    BP6?: number;
    BP7?: number;
    BS1?: number;
    BS2?: number;
    BS3?: number;
    BS4?: number;
};

export type GetPositionData = {
    query: {
        /**
         * Alternate allele.
         */
        alt: string;
        /**
         * Genome build (e.g., hg19, hg38).
         */
        build: 'hg19' | 'hg38';
        /**
         * Chromosome number.
         */
        chr: string;
        /**
         * Position on the chromosome.
         */
        pos: number;
        /**
         * The type of query being performed, typically 'position'.
         */
        queryType: string;
        /**
         * Reference allele.
         */
        ref: string;
    };
};

export type GetPositionResponse = ((VariantResponse | {
    [key: string]: unknown;
}));

export type GetPositionError = unknown;