export const API_INTERNAL_BASE_PREFIX = '/internal/'
export const API_INTERNAL_BASE_PREFIX_ANNONARS = '/internal/proxy/annonars'
export const API_INTERNAL_BASE_PREFIX_MEHARI = '/internal/proxy/mehari'
export const API_INTERNAL_BASE_PREFIX_VIGUNO = '/internal/proxy/viguno'
export const API_INTERNAL_BASE_PREFIX_NGINX = '/internal/proxy/nginx'
export const API_INTERNAL_BASE_PREFIX_DOTTY = '/internal/proxy/dotty'
export const API_INTERNAL_BASE_PREFIX_CADA_PRIO = '/internal/proxy/cada-prio'
export const API_V1_BASE_PREFIX = '/api/v1/'
