"""init bookmarks

Revision ID: 27c3977494f7
Revises: 8ccd31a4f116
Create Date: 2023-10-27 09:40:49.740067+02:00

"""
import fastapi_users_db_sqlalchemy.generics  # noqa
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "27c3977494f7"
down_revision = "8ccd31a4f116"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookmarks",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("user", sa.Uuid(), nullable=False),
        sa.Column(
            "obj_type", sa.Enum("seqvar", "strucvar", "gene", name="bookmarktypes"), nullable=False
        ),
        sa.Column("obj_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["user"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user", "obj_type", "obj_id", name="uq_bookmark"),
    )
    op.create_index(op.f("ix_bookmarks_id"), "bookmarks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookmarks_id"), table_name="bookmarks")
    op.drop_table("bookmarks")
    # ### end Alembic commands ###

    sa.Enum(name="bookmarktypes").drop(op.get_bind(), checkfirst=False)
