"""init acmgseqvar

Revision ID: 44fcdd33bf03
Revises: d10fec1c88fc
Create Date: 2023-11-29 11:21:01.073814+01:00

"""
import fastapi_users_db_sqlalchemy.generics  # noqa
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "44fcdd33bf03"
down_revision = "d10fec1c88fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
