"""initialize clinvarsub tables

Revision ID: 850ccab0221d
Revises: d10fec1c88fc
Create Date: 2023-12-15 12:32:49.537941+01:00

"""

import fastapi_users_db_sqlalchemy.generics  # noqa
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "850ccab0221d"
down_revision = "d10fec1c88fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinvarsubuserorg",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("owner", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("clinvar_api_token", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["owner"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clinvarsubuserorg_id"), "clinvarsubuserorg", ["id"], unique=False)
    op.create_table(
        "clinvarsubthread",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("submittingorg_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=False),
        sa.Column("primary_variant_desc", sa.String(length=1024), nullable=False),
        sa.Column("effective_scv", sa.String(length=32), nullable=True),
        sa.Column(
            "effective_presence",
            sa.Enum("ABSENT", "PRESENT", name="variantpresence"),
            nullable=True,
        ),
        sa.Column(
            "desired_presence", sa.Enum("ABSENT", "PRESENT", name="variantpresence"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "INITIAL",
                "WAITING",
                "IN_PROGRESS",
                "SUCCESS",
                "FAILED",
                name="submissionthreadstatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["submittingorg_id"], ["clinvarsubuserorg.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "clinvarsubthread_variantid", "clinvarsubthread", ["primary_variant_desc"], unique=False
    )
    op.create_index(op.f("ix_clinvarsubthread_id"), "clinvarsubthread", ["id"], unique=False)
    op.create_table(
        "clinvarsubactivity",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column(
            "submissionthread_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column(
            "kind",
            sa.Enum("RETRIEVE", "CREATE", "UPDATE", "DELETE", name="submissionactivitykind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "INITIAL",
                "WAITING",
                "IN_PROGRESS",
                "COMPLETE_SUCCESS",
                "COMPLETE_FAILURE",
                "COMPLETE_IN_PROGRESS",
                "FAILED",
                "TIMEOUT",
                name="submissionactivitystatus",
            ),
            nullable=False,
        ),
        sa.Column("request_payload", sa.JSON(), nullable=True),
        sa.Column("request_timestamp", sa.DateTime(), nullable=True),
        sa.Column("response_payload", sa.JSON(), nullable=True),
        sa.Column("response_timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["submissionthread_id"], ["clinvarsubthread.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clinvarsubactivity_id"), "clinvarsubactivity", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clinvarsubactivity_id"), table_name="clinvarsubactivity")
    op.drop_table("clinvarsubactivity")
    op.drop_index(op.f("ix_clinvarsubthread_id"), table_name="clinvarsubthread")
    op.drop_index("clinvarsubthread_variantid", table_name="clinvarsubthread")
    op.drop_table("clinvarsubthread")
    op.drop_index(op.f("ix_clinvarsubuserorg_id"), table_name="clinvarsubuserorg")
    op.drop_table("clinvarsubuserorg")
    # ### end Alembic commands ###

    sa.Enum(name="submissionthreadstatus").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="variantpresence").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="submissionactivitystatus").drop(op.get_bind(), checkfirst=False)
    sa.Enum(name="submissionactivitykind").drop(op.get_bind(), checkfirst=False)
