"""init adminmsgs

Revision ID: 8ccd31a4f116
Revises: c8009ed33089
Create Date: 2023-09-28 10:41:57.671434+02:00

"""
import fastapi_users_db_sqlalchemy.generics  # noqa
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8ccd31a4f116"
down_revision = "c8009ed33089"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adminmessages",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("active_start", sa.DateTime(), nullable=False),
        sa.Column("active_stop", sa.DateTime(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_adminmessages_id"), "adminmessages", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_adminmessages_id"), table_name="adminmessages")
    op.drop_table("adminmessages")
    # ### end Alembic commands ###
