"""init acmgseqvar
Revision ID: d10fec1c88fc
Revises: 4f3b20f156c1
Create Date: 2023-11-29 11:16:25.636296+01:00

"""
import fastapi_users_db_sqlalchemy.generics  # noqa
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d10fec1c88fc"
down_revision = "4f3b20f156c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "acmgseqvar",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("user", sa.Uuid(), nullable=False),
        sa.Column("seqvar_name", sa.String(length=255), nullable=False),
        sa.Column("acmg_rank", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["user"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user", "seqvar_name", name="uq_acmgseqvar"),
    )
    op.create_index(op.f("ix_acmgseqvar_id"), "acmgseqvar", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_acmgseqvar_id"), table_name="acmgseqvar")
    op.drop_table("acmgseqvar")
    # ### end Alembic commands ###
