<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'

import { AuthClient } from '@/api/auth'
import { UsersClient } from '@/api/users'
import { UtilsClient } from '@/api/utils'
import { type OAuthAccount, useUserStore } from '@/stores/user'

const userStore = useUserStore()

const router = useRouter()

/** Stores the email address for sending test email. */
const testEmailTo = ref<string>('')

/** Send out test email via API for superusers. */
const sendTestEmail = async () => {
  const utilsClient = new UtilsClient()
  await utilsClient.sendTestEmail(testEmailTo.value)
}

const logout = async () => {
  const authClient = new AuthClient()
  await authClient.logout()

  userStore.loadCurrentUser()

  router.push('/')
}

/** Model that allows user to update their email. */
const updateEmailValue = ref<string>('')

/** Model for the update email dialog. */
const updateEmailShowDialog = ref<boolean>(false)

/** Triggers the update of the email value and trigger request for verification. */
const updateAndVerifyEmail = async () => {
  const usersClient = new UsersClient()
  await usersClient.updateUserProfile({ email: updateEmailValue.value })
  await userStore.loadCurrentUser()
  const authClient = new AuthClient()
  await authClient.requestVerifyToken(updateEmailValue.value)

  updateEmailShowDialog.value = false
}

/** Returns whether the user's email looks like an automatically generated one
 * from OrcID and thus needs change.
 */
const looksLikeAutogeneratedFromOrcid = () => {
  if (userStore.currentUser) {
    const regex = /^needs-update-.*orcid.example.org$/
    return regex.test(userStore.currentUser?.email ?? '')
  } else {
    return false
  }
}

/** Returns the OrcID OAuth account, if any. */
const orcidAccount = computed<OAuthAccount | null>(() => {
  const account = userStore.currentUser?.oauth_accounts?.find(
    (account) => account.oauth_name === 'orcid'
  )
  return account ?? null
})

/** Returns the LifeScience RI OAuth account, if any. */
const lsriAccount = computed<OAuthAccount | null>(() => {
  const account = userStore.currentUser?.oauth_accounts?.find(
    (account) => account.oauth_name === 'lifescience_ri'
  )
  return account ?? null
})

/** Triger account association with the given provider. */
const handleProviderAssociation = async (name: string) => {
  const redirectTo = new URLSearchParams(window.location.search).get('redirectTo')

  const provider = userStore.oauth2Providers.find((provider) => provider.name === name)
  if (!provider) {
    throw new Error(`No provider found for name ${name}`)
  }

  const authClient = new AuthClient()
  const redirectUrl = await authClient.fetchOAuth2AssociateUrl(provider, redirectTo)
  window.location.href = redirectUrl
}

onMounted(async () => {
  await userStore.initialize()
  updateEmailValue.value = userStore.currentUser?.email ?? ''
})
</script>

<template>
  <div v-if="userStore.currentUser">
    <v-card class="mt-0">
      <v-card-title>Profile Information</v-card-title>

      <v-row class="align-center fill-height" justify="center">
        <v-col cols="6">
          <v-card class="mb-5 ml-5" elevation="0" min-width="400" max-width="448">
            <v-card-item>
              <v-card-title>User Profile</v-card-title>

              <v-card-subtitle> You are currently logged in... </v-card-subtitle>
            </v-card-item>

            <v-card-text>
              <v-form class="mt-3">
                <v-text-field v-model="userStore.currentUser.email" label="Email" readonly />
                <div v-if="!userStore.currentUser.is_verified" class="text-red-darken-3">
                  Please verify your email to use all features of the site and persist the account.
                  <template v-if="looksLikeAutogeneratedFromOrcid()">
                    OrcID did not give us access to your email so we placed a temporary one that you
                    will need to update and verify.
                  </template>
                </div>

                <div class="text-center">
                  <v-btn color="primary" class="text-center">
                    Update Email...

                    <v-dialog v-model="updateEmailShowDialog" activator="parent" width="auto">
                      <v-card
                        title="Update Email"
                        subtitle="Update your email address and request verification."
                      >
                        <v-card-item>
                          <v-text-field v-model="updateEmailValue" label="Email" />
                          <v-card-actions>
                            <v-btn
                              color="primary"
                              prepend-icon="mdi-send"
                              @click="updateAndVerifyEmail"
                            >
                              Update Email and Request Verification
                            </v-btn>
                            <v-btn color="secondary" @click="updateEmailShowDialog = false">
                              Cancel
                            </v-btn>
                          </v-card-actions>
                        </v-card-item>
                      </v-card>
                    </v-dialog>
                  </v-btn>
                </div>

                <div class="mt-3">Status</div>
                <v-checkbox
                  v-if="userStore.currentUser.is_superuser"
                  v-model="userStore.currentUser.is_superuser"
                  label="is superuser"
                  readonly
                />
                <v-checkbox
                  v-model="userStore.currentUser.is_verified"
                  label="verified email"
                  readonly
                />
                <v-checkbox
                  v-model="userStore.currentUser.is_active"
                  label="active user"
                  readonly
                />

                <div class="mt-3">Sign-In Options</div>
                <div>
                  <div>
                    <v-sheet
                      v-if="orcidAccount?.id"
                      elevation="2"
                      border
                      rounded
                      class="px-3 py-3 my-2"
                    >
                      <div>Your OrcID has been connected successfully.</div>
                      <div>
                        <a :href="`https://orcid.org/${orcidAccount.account_id}`">
                          <img
                            style="vertical-align: middle; width: 20px"
                            src="@/assets/orcid.svg"
                          />
                          {{ orcidAccount.account_id }}
                        </a>
                      </div>
                    </v-sheet>
                    <v-sheet
                      v-else
                      elevation="2"
                      border
                      rounded
                      class="px-3 py-3 my-2"
                      @click="handleProviderAssociation('orcid')"
                    >
                      <img
                        style="vertical-align: middle; width: 50px"
                        src="@/assets/orcid.svg"
                        class="float-left pr-3"
                      />
                      No OrcID connected yet. Click here to connect your OrcID.
                    </v-sheet>
                  </div>
                </div>
                <div>
                  <div>
                    <v-sheet
                      v-if="lsriAccount?.id"
                      elevation="2"
                      border
                      rounded
                      class="px-3 py-3 my-2"
                    >
                      <div>Your LifeScience RI Account has been connected successfully.</div>
                      <div>
                        {{ lsriAccount.account_id }}
                      </div>
                    </v-sheet>
                    <v-sheet
                      v-else
                      elevation="2"
                      border
                      rounded
                      class="px-3 py-3 my-2"
                      @click="handleProviderAssociation('lifescience_ri')"
                    >
                      LifeScience RI not connected yet. Click here to connect.
                    </v-sheet>
                  </div>
                </div>
              </v-form>

              <v-row class="pt-6" justify="center">
                <v-btn id="login" prepend-icon="mdi-key-variant" @click="logout"> Logout </v-btn>
              </v-row>
            </v-card-text>
          </v-card>
        </v-col>
        <v-col cols="6">
          <v-card
            class="mx-auto pa-4 pb-8 mt-12"
            elevation="0"
            min-width="400"
            max-width="448"
          >
            <v-card-item>
              <v-card-title>Send test Email</v-card-title>
              <v-card-subtitle>(Only superusers can do this)</v-card-subtitle>

              <v-card-item>
                <v-text-field v-model="testEmailTo" label="Email Recipient" />

                <v-btn block prepend-icon="mdi-send" class="mt-2" @click="sendTestEmail">
                  Send Test Email
                </v-btn>
              </v-card-item>
            </v-card-item>
          </v-card>
        </v-col>
      </v-row>
    </v-card>
  </div>
</template>
